# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./ /app/
RUN dotnet restore CosmosDBSync.CLI

# Copy everything else and build
RUN dotnet publish CosmosDBSync.CLI -c Release -o out --no-restore

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "cosmossync.dll", "--", "-i"]